language: python
sudo: false

matrix:
  include:
   - python: 3.5
     env: COVERAGE=true
   

install:
  - python setup.py install

script:
  - which nosetests
  - which sisl
  - ldd sisl
  - nosetests --exe sisl

after_success:
  - if [[ ${COVERAGE:-false} != false ]]; then bash <(curl -s https://codecov.io/bash) ; fi


#
# These are setup scripts:
#

addons:
  apt:
    packages: &common_packages
      - gfortran
      - libhdf5-serial-dev 
      - libnetcdf-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

before_install:
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh ;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh -O miniconda.sh ;
    fi
  - echo $PATH
  - bash miniconda.sh -b
  - echo $PATH
  - export PATH=$HOME/miniconda/bin:$PATH
  - echo $PATH
  - which conda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
# Do actual package installations
  - conda info -a
  - echo "nose" >> requirements.txt
  - echo $PATH
  - conda create -q -n test-environment --file requirements.txt
  - source activate test-environment
