language: python
sudo: required

matrix:
  include:
   - python: 3.5
     env: COVERAGE=true
   
script:
  - which sisl
  - ldd sisl
  - nosetests --exe sisl

after_success:
  - if [[ ${COVERAGE:-false} != false ]]; then bash <(curl -s https://codecov.io/bash) ; fi

#
# These are setup scripts:
#

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - echo "nose" >> requirements.txt

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION  --file requirements.txt
  - source activate test-environment
  - python setup.py install


addons:
  apt:
    packages: &common_packages
      - gfortran
      - libhdf5-serial-dev 
      - libnetcdf-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

